### ISSUE TITLE
Running non-python tools on data in Azure Machine Learning Pipeline steps

### ISSUE THREAD

**Issue by h2floh** [liupeirong/MLOpsManufacturing#12]
Currently Azure Machine Learning SDK only allows R or Python scripts to be executed from within a Azure Machine Learning Pipeline step.

The requirement is that other tools should be able to be packed and executed in a AML Pipeline step.

One way is to leverage [pythons subprocess](https://pythonspot.com/python-subprocess/#:~:text=%20Python%20Subprocess%20%201%20Start%20a%20process,it%20in%20a%20string%20directly%20using...%20More%20) feature to execute any command line tool.

Drawbacks will be native reporting back to AMLS. The STDOUT STDERR results need to be parsed based on the concrete tool run to e.g. report back metrics.

**Comment by liupeirong** [comment]
Maybe we can create a simple sample that wraps a C++ executable inside a Python step of an Azure ML pipeline. The step should correct retrieve the success or failure of the executable run.

**Comment by h2floh** [comment]
@liupeirong, our example is based on just executing 'cp' command and copy the pipeline step input data to the pipeline step output. I think showing how the data flows is most important. Just executing something is very simple.
