### ISSUE TITLE
Integrate Azure-MLOps Hub CLI

### ISSUE THREAD

**Issue by h2floh** [liupeirong/MLOpsManufacturing#24]
I would like to explore how we can leverage the [The CLI of Azure-MLOps Hub for Manufacturing](https://github.com/MFG-Azure-MLOps-Hub/CLI) for this repo as an addition installation option. Or provide this repo as an additional template for [Azure-MLOps-Hub](https://github.com/MFG-Azure-MLOps-Hub).

Next Steps:
- [ ] Understand how the CLI is working
- [ ] Discuss with @gary918 and @maye-msft the option how we could leverage the CLI without copying code (CLI installer)
- [ ] Discuss with @gary918 and @maye-msft the option what needs to be done to add this repo as a template to the Hub

**Comment by liupeirong** [comment]
Close for now until the cli gains more traction.
