### ISSUE TITLE
Wrap custom business logic in AML pipeline

### ISSUE THREAD

**Issue by liupeirong** [liupeirong/MLOpsManufacturing#38]
Wrap existing ML scripts into AML pipeline steps. Provide best practices, samples.

**Comment by h2floh** [comment]
## Glossary
| Term | Remark |
| --------------- | --------------- | 
| custom(er) business logic | the scripts (mainly python but not only, example [here](https://github.com/liupeirong/MLOpsManufacturing/blob/main/samples/image-classification-tensorflow/ml_model/train/train.py)) which need to be wrapped/executed from a python script containing the AML SDK run glue like [here](https://github.com/liupeirong/MLOpsManufacturing/blob/main/samples/image-classification-tensorflow/ml_model/train/train_aml.py). You could think of it as the ML train/prep scripts but some steps could be not directly related to ML so we choose a broader term |

## Scenario or use case

A new MLOps project is starting. The likelihood is high that (python) scripts exists to do the data preparation, machine learning training, evaluation. Most likely the goal of a MLOps project will be to operationalize the existing ML foundation (scripts). Users of this repository are searching for best practices and examples how to do this, step by step and what should be checked and made ready in advance for a successful wrapping.

The project teams worked out already patterns and gained a lot of insights how to do this efficiently. **We define these patterns for now as best practice**.

## Acceptance criteria

- [x] One [sample](https://github.com/liupeirong/MLOpsManufacturing/tree/main/samples) which applies the best practice pattern in code
- [x] Best Practice [documentation](https://github.com/liupeirong/MLOpsManufacturing/tree/main/docs) on things to watch for (e.g. how to deal with parameters, how to modify existing business logic to be able to be wrapped, how to do a dependency analysis [think of pip packages etc] of business logic) the exact scope of the documentation needs to be defined by the team working on it, currently I have too little insights what was learned so far in detail

## Stretch Goal

- [ ] Apply the same patterns/best practices to all existing [samples](https://github.com/liupeirong/MLOpsManufacturing/tree/main/samples)

**Comment by h2floh** [comment]
The sample introduced with #65 is explaining the process of wrapping existing ML scripts (custom business logic) into AML pipelines.
