### ISSUE TITLE
RBAC for source code in AML portal

### ISSUE THREAD

**Issue by liupeirong** [liupeirong/MLOpsManufacturing#39]
Investigate if it's possible to do role based access control for source code in Azure ML portal. Provide additional security best practice to the [AML security post](https://github.com/liupeirong/MLOpsManufacturing/blob/main/docs/azureml-security.md).

**Comment by h2floh** [comment]
## Discussion points

- Should we split this into two issues, one for RBAC in the Studio and one for Security Best Practice from the AML Security post?

## Glossary
| Term | Remark |
| --------------- | --------------- | 
| RBAC | Azure Machine Learning Studio & Azure Portal Role Based Access |

## Scenario or use case

Machine Learning gets more crucial and central to run businesses successfully. Therefore the IP and sensitive information as well as input data and the model result needs to be secured. For enterprises the requirements on level of IT security and RBAC are very sophisticated therefore we need to incorporate all possible security best practices into the samples to demonstrate that it can be run safely in a modern cloud native security driven approach.

The project teams worked on these topics and can incorporate their insights and best practices to all dimensions of an AML project

## Acceptance criteria

- [ ] One [sample](https://github.com/liupeirong/MLOpsManufacturing/tree/main/samples) which applies the security best practice & RBAC patterns in code
- [ ] Best Practice [documentation](https://github.com/liupeirong/MLOpsManufacturing/tree/main/docs) on things to watch for and create secured processes (e.g. code access, PR review and release guidelines, hardened Infrastructure [as Code], use of KeyVault, Virtual Networks, RBAC settings and Matrixes ...) the exact scope of the documentation needs to be defined by the team working on it, currently I have too little insights what was learned so far in detail

## Stretch Goal

- [ ] Apply the same patterns/best practices to all existing [samples](https://github.com/liupeirong/MLOpsManufacturing/tree/main/samples)
