### ISSUE TITLE
Azure ML SDK mocking and unit testing

### ISSUE THREAD

**Issue by liupeirong** [liupeirong/MLOpsManufacturing#40]
Some of this work is demonstrated in [this sample](https://github.com/liupeirong/MLOpsManufacturing/tree/main/samples/non-python-preprocess/ml_service/tests/pipelines). This item is to 
1. Make it more generic and reusable. Put it in the `common` folder since it's a cross-cutting concern.
2. Create more unit tests in samples to demonstrate its usage.

**Comment by h2floh** [comment]
## Glossary
| Term | Remark |
| --------------- | --------------- | 
|  |  |

## Scenario or use case

For new MLOps projects based on AMLS, instead that every project team needs to reinvent mocking strategies for the AML SDK we are searching for a reusable pattern which can be copied and directly applied to the code to test (e.g. AML pipeline build scripts).

**The v-team identified one possible solution to independently create mocks for relevant AML SDK features. The current sample may not yet be complete, there may be other and better solutions. See this backlog as a verification if you are able to reuse the current idea easily for your additional samples.** 

**Additional input, ideas, extensions from everyone is very much welcomed!**

## Acceptance criteria

- [ ] One new [sample](https://github.com/liupeirong/MLOpsManufacturing/tree/main/samples) applying the [pytest fixture approach for mocking relevant AML SDK features](https://github.com/liupeirong/MLOpsManufacturing/tree/main/samples/non-python-preprocess/ml_service/tests/pipelines) and extend it if needed
- [ ] Put the (fixture) scripts and dependencies as a template into the `common` area
- [ ] [Documentation](https://github.com/liupeirong/MLOpsManufacturing/tree/main/docs) on how to copy the template and write adapt AML SDK related unit tests when starting a new project, explain the inner workings of the approach

## Stretch Goal

- [ ] Apply AML SDK unit tests to all existing [samples](https://github.com/liupeirong/MLOpsManufacturing/tree/main/samples)
- [ ] Update all [samples](https://github.com/liupeirong/MLOpsManufacturing/tree/main/samples) already using the approach to the latest template version from `common`
