### ISSUE TITLE
Create a sample to trigger Azure ML pipelines from Azure Functions

### ISSUE THREAD

**Issue by liupeirong** [liupeirong/MLOpsManufacturing#42]
1. Document on why and what we want to demonstrate in this sample. 
2. Create unit tests for the sample.
3. Create CI/CD pipelines for the sample.

**Comment by h2floh** [comment]
## Glossary
| Term | Remark |
| --------------- | --------------- | 
|  |  |

## Scenario or use case

One of the reasons doing MLOps is to automate all the steps needed from source(raw?) data to the deployment of a model for inference. With that automation in place it is just a natural step to trigger these automated runs when the source data changes. We want to demonstrate how to use Azure Functions to trigger the AML pipeline on changes to the source data in a data store.

**The project teams implemented this feature already in the field.**

## Acceptance criteria

- [ ] One [sample](https://github.com/liupeirong/MLOpsManufacturing/tree/main/samples) which includes the deployment and usage of a Azure Function triggering the(several) AML pipeline(s) based on new data arriving in a data store
- [ ] Unit tests for the Azure Function code
- [ ] CI/CD pipelines for the Azure Function part
- [ ] Architecture explanation [documentation](https://github.com/liupeirong/MLOpsManufacturing/tree/main/docs) (e.g. include pros/cons of various trigger strategies like interval check vs real event driven approaches, how to detect/ensure that source data is completely transferred before triggering the AML pipeline etc.)

## Stretch Goal

- [ ] Integration tests for the Azure Function trigger
