### ISSUE TITLE
Azure ML Pipeline Steps - appendable template

### ISSUE THREAD

**Issue by liupeirong** [liupeirong/MLOpsManufacturing#48]

**Comment by h2floh** [comment]
## Glossary
| Term | Remark |
| --------------- | --------------- | 
|  |  |

## Scenario or use case

The way provided by the AML SDK to build/publish AML pipelines is a [python script](https://docs.microsoft.com/en-us/azure/machine-learning/how-to-create-machine-learning-pipelines#steps) invoking AML SDK features/methods. This opens up unlimited possibilities on how to specify the AML pipelines but we want to start in a new MLOps project with a best practice way of streamline or code style these AML pipeline build scripts.

**The project teams developed a best practice pattern to encapsulate AML pipeline steps as classes and easily append them in a structured way.**
**All teams should use this pattern for new samples**

## Acceptance criteria

- [ ] One [sample](https://github.com/liupeirong/MLOpsManufacturing/tree/main/samples) applying this pattern
- [ ] [Documentation](https://github.com/liupeirong/MLOpsManufacturing/tree/main/docs) documenting this best practice pattern, in addition a template for the root AML pipeline build script with different sections could be defined

## Stretch Goal

- [ ] Refactor all [samples](https://github.com/liupeirong/MLOpsManufacturing/tree/main/samples) applying this best practice pattern
